In [10]:
%pip install --user networkx
%pip install --user numpy
%pip install --user matplotlib
%pip install --user scipy

Note: you may need to restart the kernel to use updated packages.


You should consider upgrading via the 'c:\Users\Mostafa\AppData\Local\Programs\Python\Python39\python.exe -m pip install --upgrade pip' command.


Note: you may need to restart the kernel to use updated packages.


You should consider upgrading via the 'c:\Users\Mostafa\AppData\Local\Programs\Python\Python39\python.exe -m pip install --upgrade pip' command.


Note: you may need to restart the kernel to use updated packages.


You should consider upgrading via the 'c:\Users\Mostafa\AppData\Local\Programs\Python\Python39\python.exe -m pip install --upgrade pip' command.


     --------------------------------------- 42.5/42.5 MB 24.3 MB/s eta 0:00:00
Note: you may need to restart the kernel to use updated packages.


You should consider upgrading via the 'c:\Users\Mostafa\AppData\Local\Programs\Python\Python39\python.exe -m pip install --upgrade pip' command.


In [5]:
import numpy as np
import networkx as nx
import matplotlib.pyplot as plt


### Main Program

### Helper Functions

In [6]:
def d(G, u, v):
    # Returns shortest distance between 2 nodes in conncected graph
    path = nx.shortest_path(G, u, v, weight='weight') # Get list of nodes in shortest path
    distance = 0 
    for i in range(0, len(path)-1): # Add weight of each edge in path to total distance
        source, target = path[i:i+2] 
        distance += G[source][target]['weight']
    return distance

def P(G, u, v):
    # Returns shortest distance between 2 nodes, or None if no path exists
    if(not nx.has_path(G, u, v)):
        return None
    return d(G, u, v)

def print_graph(G):
    # Prints matrix representation and edges of networksx Graph object
    print(nx.adjacency_matrix(G).todense(), '\n')
    print('edges: \n')
    for edge in G.edges(data=True):
        print(edge)
    print()

In [35]:
def Spanner(G, r):
    """Algorithm for finding an r-spanner of a given graph
    
    Args:
        G: networkx Graph object to find spanner of
        r: stretch factor 

    Returns:
        H: networks Graph object representing the r-spanner of G
    """
    H = nx.Graph()
    H.add_nodes_from(G)
    edges=sorted(G.edges(data=True), key=lambda t: t[2].get('weight', 1))
    print(edges)
    for edge in edges:
        span = r*edge[2]['weight']
        distance = P(H, edge[0], edge[1])
        if distance == None:
            distance = float("inf")
        if span < distance:
            H.add_edge(edge[0], edge[1], weight=edge[2]['weight'])
    return H

### Run program with example graph

In [36]:
g_matrix = np.array([[0, 2, 4 , 1],  # Initialize numpy matrix, node numbers start at 0
                     [2, 0, 1 , 2], 
                     [4, 1, 0 , 1], 
                     [1, 2, 1 , 0]])
G = nx.from_numpy_array(g_matrix)   # Convert to networkx Graph object
r = 3                                # Set stretch factor 
H = Spanner(G, r)                    # Create r-spanner

print('Original Graph, G: \n')
print_graph(G)
print('R-spanner Graph, H: \n')
print_graph(H)

[(0, 3, {'weight': 1}), (1, 2, {'weight': 1}), (2, 3, {'weight': 1}), (0, 1, {'weight': 2}), (1, 3, {'weight': 2}), (0, 2, {'weight': 4})]
Original Graph, G: 

[[0 2 4 1]
 [2 0 1 2]
 [4 1 0 1]
 [1 2 1 0]] 

edges: 

(0, 1, {'weight': 2})
(0, 2, {'weight': 4})
(0, 3, {'weight': 1})
(1, 2, {'weight': 1})
(1, 3, {'weight': 2})
(2, 3, {'weight': 1})

R-spanner Graph, H: 

[[0 0 0 1]
 [0 0 1 0]
 [0 1 0 1]
 [1 0 1 0]] 

edges: 

(0, 3, {'weight': 1})
(1, 2, {'weight': 1})
(2, 3, {'weight': 1})



### Query graphs to check if stretch property is satisfied

In [37]:
# Check verticies 0 and 1 on both graphs
u, v = 0, 1
distanceG, distanceH = d(G,u,v), d(H, u, v)
print(distanceH <= distanceG * r)

# Check verticies 1 and 2 on both graphs
u, v = 1, 2
distanceG, distanceH = d(G,u,v), d(H, u, v)
print(distanceH <= distanceG * r)

True
True
